package Core::Const;
use v5.14;

use base qw(Exporter);

our @EXPORT = qw(
    SUCCESS
    FAIL

    STATUS_INIT
    STATUS_WAIT_FOR_PAY
    STATUS_PROGRESS
    STATUS_ACTIVE
    STATUS_BLOCK
    STATUS_REMOVED
    STATUS_ERROR

    EVENT_CREATE
    EVENT_BLOCK
    EVENT_BLOCK_FORCE
    EVENT_REMOVE
    EVENT_PROLONGATE
    EVENT_ACTIVATE
    EVENT_ACTIVATE_FORCE
    EVENT_CHILD_PREFIX
    EVENT_NOT_ENOUGH_MONEY
    EVENT_CHANGED
    EVENT_CHANGED_TARIFF
    EVENT_CHANGED_TICKET

    TASK_NEW
    TASK_SUCCESS
    TASK_FAIL
    TASK_DELAYED
    TASK_STUCK
    TASK_PAUSED

    GROUP_ID_LOCAL
    GROUP_ID_MAIL

    TICKET_OPEN
    TICKET_IN_PROGRESS
    TICKET_WAITING
    TICKET_CLOSED
    TICKET_ARCHIVED
    TICKET_LOW
    TICKET_NORMAL
    TICKET_HIGH
    TICKET_URGENT
    TICKET_SERVICE
    TICKET_PAYMENT
    TICKET_OTHER
);

use constant {
    SUCCESS => 1,
    FAIL => 0,
};

use constant {
    STATUS_INIT => 'INIT',
    STATUS_WAIT_FOR_PAY => 'NOT PAID',
    STATUS_PROGRESS => 'PROGRESS',
    STATUS_ACTIVE => 'ACTIVE',
    STATUS_BLOCK => 'BLOCK',
    STATUS_REMOVED => 'REMOVED',
    STATUS_ERROR => 'ERROR',
};

use constant {
    CLIENT_FIZ => 0,
    CLIENT_JUR => 1,
    CLIENT_IP => 2,
    CLIENT_FIZ_NR => 3,
    CLIENT_JUR_NR => 4,
};

use constant {
    EVENT_CREATE => 'CREATE',
    EVENT_NOT_ENOUGH_MONEY => 'NOT_ENOUGH_MONEY',
    EVENT_BLOCK => 'BLOCK',
    EVENT_BLOCK_FORCE => 'BLOCK FORCE',
    EVENT_REMOVE => 'REMOVE',
    EVENT_PROLONGATE => 'PROLONGATE',
    EVENT_ACTIVATE => 'ACTIVATE',
    EVENT_ACTIVATE_FORCE => 'ACTIVATE FORCE',
    EVENT_CHANGED => 'CHANGED',
    EVENT_CHANGED_TARIFF => 'CHANGED_TARIFF',
    EVENT_CHANGED_TICKET => 'CHANGED_TICKET',
};

use constant {
    TASK_NEW => 'NEW',
    TASK_SUCCESS => 'SUCCESS',
    TASK_FAIL => 'FAIL',
    TASK_DELAYED => 'DELAYED',
    TASK_STUCK => 'STUCK',
    TASK_PAUSED => 'PAUSED',
};

use constant {
    GROUP_ID_LOCAL => 1,
    GROUP_ID_MAIL => 2,
};

use constant {
    TICKET_OPEN => 'open',
    TICKET_IN_PROGRESS => 'in_progress',
    TICKET_WAITING => 'waiting',
    TICKET_CLOSED => 'closed',
    TICKET_ARCHIVED => 'archived',
    TICKET_LOW => 'low',
    TICKET_NORMAL => 'normal',
    TICKET_HIGH => 'high',
    TICKET_URGENT => 'urgent',
    TICKET_SERVICE => 'service',
    TICKET_PAYMENT => 'payment',
    TICKET_OTHER => 'other',
};

1;

